https://{default}/:
  primary: null
  id: null
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  tls:
    strict_transport_security:
      enabled: true
      include_subdomains: true
      preload: true
    min_version: null
    client_authentication: null
    client_certificate_authorities: []
  cache:
    enabled: true
    default_ttl: 0
    cookies:
    - /^SS?ESS/
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: app:http
